exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.lewd = require('./lewd')
exports.urlShortener = require('./shortener')
exports.fetish = require('./fetish')
exports.waifu = require('./waifu')