exports.cekResi = require('./cekResi')
exports.downloader = require('./downloader')
exports.meme = require('./meme')
exports.ecchi = require('./ecchi')
exports.urlShortener = require('./shortener')
exports.translate = require('./translate')
exports.getLocationData = require('./location')